- dataTypes:
  - wineventlog
  name: Access To Browser Credential Files By Uncommon Applications - Security
  impact:
    confidentiality: 1
    integrity: 1
    availability: 2
  category: Security Detection
  technique: T1555.003
  adversary: UNKNOWN
  description: Detects file access requests to browser credential stores by uncommon
    processes. Could indicate potential attempt of credential stealing This rule requires
    heavy baselining before usage.
  references:
  - https://ipurple.team/2024/09/10/browser-stored-credentials/
  where: safe("log.eventCode", 0.0) == double(4663) && safe("log.objectType", "")
    == "File" && safe("log.accessMask", "") == "0x1" && (safe("log.objectName", "").contains("\\User
    Data\\Default\\Login Data") || safe("log.objectName", "").contains("\\User Data\\Local
    State") || safe("log.objectName", "").contains("\\User Data\\Default\\Network\\Cookies")
    || safe("log.fileName", "").endsWith("\\cookies.sqlite") || safe("log.fileName",
    "").endsWith("\\places.sqlite") || safe("log.fileName", "").endsWith("release\\key3.db")
    || safe("log.fileName", "").endsWith("release\\key4.db") || safe("log.fileName",
    "").endsWith("release\\logins.json")) && !(safe("log.processName", "") == "System"
    || safe("log.processName", "").startsWith("C:\\Program Files (x86)\\") || safe("log.processName",
    "").startsWith("C:\\Program Files\\") || safe("log.processName", "").startsWith("C:\\Windows\\system32\\")
    || safe("log.processName", "").startsWith("C:\\Windows\\SysWOW64\\")) && !(safe("log.processName",
    "").startsWith("C:\\ProgramData\\Microsoft\\Windows Defender\\") && (safe("log.processName",
    "").endsWith("\\MpCopyAccelerator.exe") || safe("log.processName", "").endsWith("\\MsMpEng.exe")))
