- dataTypes:
  - wineventlog
  name: Credential Manager Access By Uncommon Applications
  impact:
    confidentiality: 2
    integrity: 2
    availability: 2
  category: Security Detection
  technique: T1003
  adversary: UNKNOWN
  description: Detects suspicious processes based on name and location that access
    the windows credential manager and vault. Which can be a sign of credential stealing.
    Example case would be usage of mimikatz "dpapi::cred" function
  references:
  - https://hunter2.gitbook.io/darthsidious/privilege-escalation/mimikatz
  - https://www.absolomb.com/2018-01-26-Windows-Privilege-Escalation-Guide/
  where: (safe("log.fileName", "").contains("\\AppData\\Local\\Microsoft\\Credentials\\")
    || safe("log.fileName", "").contains("\\AppData\\Roaming\\Microsoft\\Credentials\\")
    || safe("log.fileName", "").contains("\\AppData\\Local\\Microsoft\\Vault\\") ||
    safe("log.fileName", "").contains("\\ProgramData\\Microsoft\\Vault\\")) && !(safe("log.image",
    "").startsWith("C:\\Program Files\\") || safe("log.image", "").startsWith("C:\\Program
    Files (x86)\\") || safe("log.image", "").startsWith("C:\\Windows\\system32\\")
    || safe("log.image", "").startsWith("C:\\Windows\\SysWOW64\\"))
