- dataTypes:
  - wineventlog
  name: Sysmon Application Crashed
  impact:
    confidentiality: 3
    integrity: 3
    availability: 3
  category: Security Detection
  technique: T1562
  adversary: UNKNOWN
  description: Detects application popup reporting a failure of the Sysmon service
  references:
  - https://github.com/nasbench/EVTX-ETW-Resources/blob/f1b010ce0ee1b71e3024180de1a3e67f99701fe4/ETWProvidersManifests/Windows10/1803/W10_1803_Pro_19700101_17134.1/WEPExplorer/Application%20Popup.xml#L36
  where: safe("log.providerName", "") == "Application Popup" && safe("log.eventCode",
    0.0) == double(26) && (safe("log.caption", "") == "sysmon64.exe - Application
    Error" || safe("log.caption", "") == "sysmon.exe - Application Error")
