- dataTypes:
  - generic
  name: Potential JNDI Injection Exploitation In JVM Based Application
  impact:
    confidentiality: 3
    integrity: 3
    availability: 3
  category: Security Detection
  technique: T1190
  adversary: UNKNOWN
  description: Detects potential JNDI Injection exploitation. Often coupled with Log4Shell
    exploitation.
  references:
  - https://www.wix.engineering/post/threat-and-vulnerability-hunting-with-application-server-error-logs
  - https://secariolabs.com/research/analysing-and-reproducing-poc-for-log4j-2-15-0
  where: '""safe("log.comSunJndiLdap", "")."" || ""safe("log.orgApacheLoggingLog4jCoreNetJndimanager",
    "")""'
